Dapp/d09/account/urls.py
from django.urls import path 
# from . import views
from account.views import home_page, MyLogin, MyLogout, csrf_token_view, web3_features
# from articles.views import ArticleListView, HomePageRedirect, MyLoginView, MyLogoutView
# from articles.views import SelfPublicationListView, ArticleDetailView, FavouriteArticleList
# from articles.views import CreateUser, CreateArticle

app_name = 'account'

urlpatterns = [
    path('account/', home_page, name="home_page"),
    path('login/', MyLogin.as_view(), name='login'),
    path('logout/', MyLogout.as_view(), name='logout'),
    path('csrf/', csrf_token_view, name='csrf_token'),
    path('web3', web3_features, name="web3")
]

Dapp/d09/chat/urls.py
from django.urls import path 
from chat.views import access_chatrooms, RoomDetailView

app_name = 'chat'

urlpatterns = [
    path('chat/', access_chatrooms, name="chose_chatrooms"),
    path('chat/room/<int:pk>/', RoomDetailView.as_view(), name="access_room")
]

Dapp/d09/d09/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('', include('chat.urls')),
]

Dapp/d09/account/models.py
from django.db import models

# Create your models here.

Dapp/d09/chat/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.


class Room(models.Model):
    #Ajouter des protections cf websocket ?
    # Only  alphanumerics, hyphens, underscores, or periods.
    name = models.CharField(max_length=64, null=False)

class Message(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=False, related_name='author')
    room = models.ForeignKey(Room, on_delete=models.CASCADE, null=False, related_name='room_messages')
    posted_date = models.DateTimeField(default=timezone.now)
    content = models.TextField(null=False)
    # room.rooms_messages.all()#Donne tout les messages associes a l'instance de room
    # user.room_author.all()#Donne l'auteur du message 

# Solutions pour avoir la liste des users connected 
    # - enregistrer dans le modele Room les user connected
    # - enregsitrer dans le consumer les user connected 
    # - utiliser Redis pour stocker 

    # Exporter des donnees
# python manage.py dumpdata auth.User chat.Room --indent 2 > fixtures/init_data.json
    # charger des donnes 
# python manage.py loaddata fixtures/init_data.json

Dapp/d09/account/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.http import JsonResponse
from django.views.decorators.csrf import ensure_csrf_cookie
from django.contrib import messages

# Create your views here.

# Vue page d'acceuil
def home_page(request):
    return render(request, 'account/home1.html')
    # return render(request, 'account/home1.html', {'form': AuthenticationForm()})

# Vue page de login
class MyLogin(View):

    def get(self, request):
        form = AuthenticationForm()
        return render(request, "account/login.html", {'form': form})

# Redirection en cas de succès
    def post(self, request):

        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()#Authenticate effectue ici
            login(request, user)
            messages.success(request, f"Welcome, {user.username} !")
            return redirect("account:home_page")
        else:
            return render(request, "account/login.html", {'form': form})

# Vue page de logout"'
class MyLogout(View):
    def get(self, request):
        if request.user.is_authenticated:
            logout(request)
            messages.success(request, "You have been successfully logged out.")
            # return JsonResponse({'success': True})
        else:
            messages.warning(request, "Impossible action. Something went wrong.")
        return redirect("account:home_page")

# Juste pour obliger Django a reset un token CSRF apres une deconnexion du user
# Et le recuperer dans le front 
@ensure_csrf_cookie
def csrf_token_view(request):
    return JsonResponse({'detail': 'CSRF token set'})

def web3_features(request):
    return render(request, "account/web3.html")

Dapp/d09/chat/views.py
from django.shortcuts import render
from django.views.generic import DetailView
from django.db.models import Q
from chat.models import Room
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy, reverse

# Create your views here.

def access_chatrooms(request):
    rooms = Room.objects.filter(
        Q(name='TennisChat') | Q(name='FootballChat') | Q(name='CookingChat')
    )
    return render(request, 'chat/access.html', {'rooms' : rooms})

@method_decorator(login_required(login_url=reverse_lazy('account:login')), name='dispatch')
class RoomDetailView(DetailView):
    model = Room
    template_name = "chat/access_room.html"
    context_object_name = 'room'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        room = self.get_object()

        # Modifier pour les 3 derniers messages ?
        messages = room.room_messages.all()
        context['room_messages'] = messages
        return context

Dapp/d09/chat/templates/chat/access.html
{% extends 'base.html' %}

{% block title %}
<title>Chat access</title>
{% endblock %}

{% block content %}

<!-- {% if messages %}
<div class="message-container">
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">{{ message }}</div>
    {% endfor %}
</div>
{% endif %} -->
<div class=" container d-flex flex-column justify-content-center align-items-center flex-grow-1 text-center">
    {% if rooms %}
        <h1 class="mt-5 mb-5">Which room do you want to enter in ?</h1>
    {% else %}
        <p>There is no avalibale room to enter in</p>
    {% endif %}
    <ul class="list-group mt-3 mb-5">
        {% for room in rooms %}
        <li class="list-group-item list-group-item-dark">
            <a class="link-dark link-underline-opacity-0" href="{% url 'chat:access_room' room.pk%}">{{ room.name }}</a>
        </li>
        {% endfor %}
    </ul>
</div>

{% endblock %}

Dapp/d09/chat/templates/chat/access_room.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>{{ room.name }}</title>
{% endblock %}

{% block content %}

{% if messages %}
<div class="message-container">
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">{{ message }}</div>
    {% endfor %}
</div>
{% endif %}
<div class="p-3 m-3">
    <div class="text-end me-5">
        <h1>Welcome on {{ room.name }}</h1>
    </div>
    <div class="d-flex flex-row">
        <div class="w-25 m-3 border-top border-light">
            <h4 class="text-center p-3">Connected users</h4>
            <ul id="users-connected" class="list-unstyled list-group"></ul>
        </div>
        <div class="bg-secondary rounded m-3 vh-100 vw-100 d-flex flex-column">
            <div id="list_messages" class="flex-grow-1 overflow-scroll m-3">
                <ul id="chat-log" class="list-unstyled list-group w-100 h-100">
                    {% for message in room_messages %}
                        <li class="m-1 text-end list-group-item bg-light">{{ message.author.username }} : {{ message.content }}</li>
                    {% endfor %}
                </ul>
            </div>
            <div class="m-3 d-flex flex-column justify-content-end align-items-end gap-2">
                <input class="form-control rounded" id="chat-message-input" type="text" size="100" style="width: 30%;">
                <input class="m-1 form-control rounded" id="chat-message-submit" type="button" value="Send" style="width: 10%;">
            </div>
        </div>
    </div>
    {{ room.id|json_script:"room-id" }}
</div>
<script type="module" src="{% static 'js/chat.js' %}"></script>
{% endblock %}

Dapp/d09/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="h-100">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    {% block title %}{% endblock %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <!-- <script type="module" src="{% static 'js/main.js' %}" defer></script> -->
    <!-- Liens Bootstrap (CDN) -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css">
</head>
<!-- <body class="bg-secondary-subtle"> -->
<body class="d-flex h-100 text-center text-bg-dark">
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
        {% include 'nav.html' %}
        {% block content %}{% endblock %}
        {% include 'footer.html' %}

    </div>
    <!-- Script Bootstrap nécéssaire pour fonctionnalités interactives -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

Dapp/d09/templates/footer.html
<footer class="mt-auto text-white-50">
    <p>
        You can find Author on 
    <a href="https://github.com/BdClement" class="text-white">Github</a>
    </p>
</footer>

Dapp/d09/templates/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark d-flex p-3 border-bottom border-light">
    <ul class="navbar-nav container-fluid d-flex">
        <li class="nav-item d-flex align-items-center h-100 ">
            <a class="nav-link d-flex align-items-center h-100" href="{% url 'account:home_page' %}"><i class="bi bi-house"></i></i></a>
        </li>
        <li class="nav-item d-flex align-items-center h-100">
            <a class="nav-link d-flex align-items-center h-100" href="{% url 'chat:chose_chatrooms' %}">Social</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item d-flex align-items-center h-100">
            <a class="nav-link d-flex align-items-center h-100" href="{% url 'account:logout' %}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item d-flex align-items-center h-100">
            <a class="nav-link d-flex align-items-center h-100" href="{% url 'account:login' %}">Login</a>
        </li>
        {% endif %}
        <!-- <li class="nav-item d-flex align-items-center h-100">
            <a id="connect-wallet" class="nav-link d-flex align-items-center h-100" href="{% url 'account:home_page' %}">Connect Wallet</a>
        </li>
        <li class="nav-item d-flex align-items-center h-100">
            <a id="disconnect-wallet" class="nav-link d-flex align-items-center h-100 d-none" href="{% url 'account:home_page' %}">Disconnect Wallet</a>
        </li> -->
        <li class="nav-item d-flex align-items-center h-100">
            <a id="web3-features" class="nav-link d-flex align-items-center h-100" href="{% url 'account:web3' %}">Web3 Portal</a>
        </li>
    </ul>
</nav>